/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBO.Matkul.Pertemuan10;

/**
 *
 * @author akbar
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.*;


public class Contoh extends javax.swing.JFrame {

    /**
     * Creates new form Contoh
     */
    
    private controllerPelanggan pl = new controllerPelanggan();
    DefaultTableModel tabelModel;
    private int tempRowSelected;

    
    public Contoh() {
        initComponents();
    }
    
    // VIEW
    private void tampilData(){
        String[] kolom = {"nama", "alamat", "email" };
        Object[][] data = new Object[pl.getArrayListSize()][3];
        int i =0;
        while(i< pl.getArrayListSize()){
            String arrayData[] = {
            pl.getListPelanggan().get(i).getNama(),
            pl.getListPelanggan().get(i).getAlamat(),
            pl.getListPelanggan().get(i).getEmail()
            };
            data[i] = arrayData;;
            i++;
        }
        tabelModel= new DefaultTableModel(data, kolom){
            @Override
            public boolean isCellEditable(int rowIndex, int collIndex){
                return false;
            }
        };
        
        tData.setModel(tabelModel);
        reset();
    }
    
    private void reset(){
        txNama.setText(null);
        txAlamat.setText(null);
        txEmail.setText(null);
    }

    //CONTROL
    public class controllerPelanggan{
        
        private ArrayList<modelPelanggan> listPelanggan = new ArrayList<modelPelanggan>();
        public controllerPelanggan() {}
        
        public controllerPelanggan(ArrayList<modelPelanggan> listPelanggan){
            this.listPelanggan = this.listPelanggan;
        }
        
        public ArrayList<modelPelanggan> getListPelanggan() {
            return listPelanggan;
        }
        
        public void setListPelanggan(ArrayList<modelPelanggan> listPelanggan){
            this.listPelanggan = listPelanggan;
        }
        
        public void insertPelanggan(String nama, String alamat, String email) {
            modelPelanggan mPelanggan = new modelPelanggan(nama, alamat, email);
            listPelanggan.add(mPelanggan);
            System.out.println("DATA TELAH DIMASUKKAN");
        }
        
        public void updatePelanggan(int index, String nama, String alamat, String email) {
            modelPelanggan mPelanggan = new modelPelanggan(nama, alamat, email);
            listPelanggan.get(index).setNama(mPelanggan.getNama());
            listPelanggan.get(index).setAlamat(mPelanggan.getAlamat());
            listPelanggan.get(index).setEmail(mPelanggan.getEmail());
            System.out.println("DATA TELAH DIPERBARUI");
        }
        
        public void deletePelanggan(int index) {
            listPelanggan.remove(index);
            System.out.println("DATA TELAH DIHAPUS");
        }
        
        public int getArrayListSize() {
            return listPelanggan.size();
        }
    }

    //MODEL
    public class modelPelanggan{
        private String nama, alamat, email;
        public modelPelanggan(){}
        
        public modelPelanggan(String nama, String alamat, String email) {
            this.nama = nama;
            this.alamat = alamat;
            this.email = email;
        }
        
        public String getNama() {
            return nama;
        }
        public String getAlamat() {
            return alamat;
        }
        public String getEmail() {
            return email;
        }
        
        public void setNama(String nama) {
            this.nama = nama;
        }
        public void setAlamat(String alamat) {
            this.alamat = alamat;
        }
        public void setEmail(String email) {
            this.email = email;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        txAlamat = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        btSimpan = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Data Pelanggan");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alamat");

        txNama.setBackground(new java.awt.Color(255, 255, 255));
        txNama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txNama.setForeground(new java.awt.Color(0, 0, 0));
        txNama.setToolTipText("");

        txAlamat.setBackground(new java.awt.Color(255, 255, 255));
        txAlamat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txAlamat.setForeground(new java.awt.Color(0, 0, 0));
        txAlamat.setToolTipText("");

        txEmail.setBackground(new java.awt.Color(255, 255, 255));
        txEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txEmail.setForeground(new java.awt.Color(0, 0, 0));
        txEmail.setToolTipText("");

        btSimpan.setBackground(new java.awt.Color(153, 153, 153));
        btSimpan.setForeground(new java.awt.Color(0, 0, 0));
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btUpdate.setBackground(new java.awt.Color(153, 153, 153));
        btUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(153, 153, 153));
        btDelete.setForeground(new java.awt.Color(0, 0, 0));
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        tData.setBackground(new java.awt.Color(153, 153, 153));
        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txNama, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txAlamat)
                                    .addComponent(txEmail))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        pl.insertPelanggan(txNama.getText().toString(), txAlamat.getText().toString(), txEmail.getText());
        JOptionPane.showMessageDialog(this, "Data Berhasil di simpan");
        tampilData();
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        pl.updatePelanggan(tempRowSelected, txNama.getText().toString(), txAlamat.getText().toString(), txEmail.getText());
        tampilData();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        pl.deletePelanggan(tempRowSelected);
        tampilData();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDataMouseClicked
        // TODO add your handling code here:
        tempRowSelected = tData.getSelectedRow();
        if(evt.getClickCount() == 2) {
            txNama.setText(pl.getListPelanggan().get(tData.getSelectedRow()).getNama());
            txAlamat.setText(pl.getListPelanggan().get(tData.getSelectedRow()).getAlamat());
            txEmail.setText(pl.getListPelanggan().get(tData.getSelectedRow()).getEmail());
        }
    }//GEN-LAST:event_tDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contoh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tData;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txNama;
    // End of variables declaration//GEN-END:variables
}
