/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBO.Matkul.Pertemuan12;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akbar
 */
public class Quiz1 extends javax.swing.JFrame {

    /**
     * Creates new form Quiz1
     */
    
    Connection conn;
    Statement cmd;
    ResultSet rs;
    DefaultTableModel mTablePerpus;
    String SQL;
    
    public Quiz1() {
        initComponents();
    }
    
    private void showTabel() {
        try {
            conn = KoneksiQuiz.getKoneksi();
            
            cmd = conn.createStatement();
            rs = cmd.executeQuery("SELECT * FROM Quiz1");
            
            //Setting kolom dari DefaultTableModel
            mTablePerpus = new DefaultTableModel(new String[] {"JUDUL", "TAHUN TERBIT", "PENGARANG", "JENIS BUKU", "LOKASI RAK", "KATEGORI", "ISBN"},0);
            
            //Pindah isi dari result set ke dalam DefaultTableModel
            if (rs.next()) {
                do {                    
                    mTablePerpus.addRow(new Object[] {rs.getString("Judul"), rs.getInt("Tahun_terbit"), rs.getString("Pengarang"), 
                        rs.getString("Jenis_buku"), rs.getString("Lokasi"), rs.getString("Kategori"), rs.getString("ISBN")});
                } while (rs.next());
                
            } /* else {
                System.out.println("Data tidak ada");
            }*/
            TablePerpus.setDefaultEditor(Object.class, null);
            TablePerpus.setModel(mTablePerpus);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }
    
    public void refresh() {
        txJudul.setText(null);
        txTahun.setText(null);
        txPengarang.setText(null);
        cbJenis.setSelectedIndex(0);
        bgRak.clearSelection();
        cbTeknologi.setSelected(false);
        cbBisnis.setSelected(false);
        cbBahasa.setSelected(false);
        cbSejarah.setSelected(false);
        txISBN.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRak = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txJudul = new javax.swing.JTextField();
        txTahun = new javax.swing.JTextField();
        txPengarang = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        rbRak1 = new javax.swing.JRadioButton();
        rbRak2 = new javax.swing.JRadioButton();
        rbRak3 = new javax.swing.JRadioButton();
        cbTeknologi = new javax.swing.JCheckBox();
        cbBisnis = new javax.swing.JCheckBox();
        cbBahasa = new javax.swing.JCheckBox();
        cbSejarah = new javax.swing.JCheckBox();
        txISBN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePerpus = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Judul");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tahun Terbit");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pengarang");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jenis Buku");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Lokasi Rak");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Kategori");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ISBN");

        txJudul.setBackground(new java.awt.Color(255, 255, 255));
        txJudul.setForeground(new java.awt.Color(0, 0, 0));

        txTahun.setBackground(new java.awt.Color(255, 255, 255));
        txTahun.setForeground(new java.awt.Color(0, 0, 0));

        txPengarang.setBackground(new java.awt.Color(255, 255, 255));
        txPengarang.setForeground(new java.awt.Color(0, 0, 0));

        cbJenis.setBackground(new java.awt.Color(255, 255, 255));
        cbJenis.setForeground(new java.awt.Color(0, 0, 0));
        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Jenis Buku---", "Nasional", "Swasta" }));

        rbRak1.setBackground(new java.awt.Color(255, 255, 153));
        bgRak.add(rbRak1);
        rbRak1.setForeground(new java.awt.Color(0, 0, 0));
        rbRak1.setText("Rak 1");

        rbRak2.setBackground(new java.awt.Color(255, 255, 153));
        bgRak.add(rbRak2);
        rbRak2.setForeground(new java.awt.Color(0, 0, 0));
        rbRak2.setText("Rak 2");

        rbRak3.setBackground(new java.awt.Color(255, 255, 153));
        bgRak.add(rbRak3);
        rbRak3.setForeground(new java.awt.Color(0, 0, 0));
        rbRak3.setText("Rak 3");

        cbTeknologi.setBackground(new java.awt.Color(255, 255, 153));
        cbTeknologi.setForeground(new java.awt.Color(0, 0, 0));
        cbTeknologi.setText("Teknologi");

        cbBisnis.setBackground(new java.awt.Color(255, 255, 153));
        cbBisnis.setForeground(new java.awt.Color(0, 0, 0));
        cbBisnis.setText("Bisnis");

        cbBahasa.setBackground(new java.awt.Color(255, 255, 153));
        cbBahasa.setForeground(new java.awt.Color(0, 0, 0));
        cbBahasa.setText("Bahasa");

        cbSejarah.setBackground(new java.awt.Color(255, 255, 153));
        cbSejarah.setForeground(new java.awt.Color(0, 0, 0));
        cbSejarah.setText("Sejarah");

        txISBN.setBackground(new java.awt.Color(255, 255, 255));
        txISBN.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbRak1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbRak2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbRak3))
                    .addComponent(txISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTeknologi)
                            .addComponent(cbBahasa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSejarah)
                            .addComponent(cbBisnis))))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbRak1)
                    .addComponent(rbRak2)
                    .addComponent(rbRak3))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbTeknologi)
                    .addComponent(cbBisnis))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBahasa)
                    .addComponent(cbSejarah))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 640, 430));

        TablePerpus.setBackground(new java.awt.Color(255, 204, 204));
        TablePerpus.setForeground(new java.awt.Color(0, 0, 0));
        TablePerpus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePerpus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePerpusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePerpus);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 860, 670));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(204, 204, 204));
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(204, 204, 204));
        btnQuit.setForeground(new java.awt.Color(0, 0, 0));
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 640, 230));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 640, 10));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("PERPUSTAKAAN UNDIKA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        showTabel();
    }//GEN-LAST:event_formWindowActivated

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            
            String kategori = "";
            if(cbTeknologi.isSelected()) {
                kategori = "Teknologi " + kategori;
            }
            if(cbBisnis.isSelected()) {
                kategori = kategori + "Bisnis ";
            }
            if(cbBahasa.isSelected()) {
                kategori = kategori + "Bahasa ";
            }
            if(cbSejarah.isSelected()) {
                kategori = kategori + "Sejarah";
            }
            
            String rak = null;
            if(rbRak1.isSelected()) {
                rak = "Rak 1";
            } else if(rbRak2.isSelected()) {
                rak = "Rak 2";
            } else if(rbRak3.isSelected()) {
                rak = "Rak 3";
            }
            
            conn = KoneksiQuiz.getKoneksi();
            SQL = "INSERT INTO Quiz1 (Judul, Tahun_terbit, Pengarang, Jenis_buku, Lokasi, Kategori, ISBN) VALUES"
                    + "('" + txJudul.getText() + "',"
                    + txTahun.getText() + ","
                    + "'" + txPengarang.getText() + "',"
                    + "'" + cbJenis.getSelectedItem().toString() + "',"
                    + "'" + rak + "',"
                    + "'" + kategori + "',"
                    + "'" + txISBN.getText() + "')";
            
            cmd = conn.createStatement();
            cmd.executeUpdate(SQL);
            JOptionPane.showMessageDialog(this, "Success");

            refresh();
            showTabel();
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int jawab = JOptionPane.showConfirmDialog(this, "Silakan Konfirmasi?");
            
            switch(jawab){
                case JOptionPane.YES_OPTION: 
                    conn = KoneksiQuiz.getKoneksi();
                    SQL = "DELETE FROM Quiz1 WHERE ISBN = '" + txISBN.getText() + "'";
                    cmd = conn.createStatement();
                    cmd.executeUpdate(SQL);
                    JOptionPane.showMessageDialog(this, "Success");
                    showTabel();
                    refresh();
                    break;
                    
                case JOptionPane.NO_OPTION:
                    break;
                    
                case JOptionPane.CANCEL_OPTION:
                    break;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            
            String kategori = "";
            if(cbTeknologi.isSelected()) {
                kategori = "Teknologi " + kategori;
            }
            if(cbBisnis.isSelected()) {
                kategori = kategori + "Bisnis ";
            }
            if(cbBahasa.isSelected()) {
                kategori = kategori + "Bahasa ";
            }
            if(cbSejarah.isSelected()) {
                kategori = kategori + "Sejarah";
            }
            
            String rak = null;
            if(rbRak1.isSelected()) {
                rak = "Rak 1";
            } else if(rbRak2.isSelected()) {
                rak = "Rak 2";
            } else if(rbRak3.isSelected()) {
                rak = "Rak 3";
            }
            
            conn = KoneksiQuiz.getKoneksi();
            SQL = "UPDATE Quiz1 SET "
                    + "Judul = " + "'" + txJudul.getText() + "',"
                    + "Tahun_terbit = " + txTahun.getText() + ","
                    + "Pengarang = " + "'" + txPengarang.getText() + "',"
                    + "Jenis_buku = " + "'" + cbJenis.getSelectedItem().toString() + "',"
                    + "Lokasi = " + "'" + rak + "',"
                    + "Kategori = " + "'" + kategori + "'"
                    + "WHERE ISBN = '" + txISBN.getText() + "'";
            
            cmd = conn.createStatement();
            cmd.executeUpdate(SQL);
            JOptionPane.showMessageDialog(this, "Success");
            showTabel();
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refresh();
        showTabel();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            conn = KoneksiQuiz.getKoneksi();
            
            cmd = conn.createStatement();
            rs = cmd.executeQuery("SELECT * FROM Quiz1 WHERE ISBN = '" + txISBN.getText() + "'");
            
            //Setting kolom dari DefaultTableModel
            mTablePerpus = new DefaultTableModel(new String[] {"JUDUL", "TAHUN TERBIT", "PENGARANG", "JENIS BUKU", "LOKASI RAK", "KATEGORI", "ISBN"},0);
            
            //Pindah isi dari result set ke dalam DefaultTableModel
            if (rs.next()) {
                do {                    
                    mTablePerpus.addRow(new Object[] {rs.getString("Judul"), rs.getInt("Tahun_terbit"), rs.getString("Pengarang"), 
                        rs.getString("Jenis_buku"), rs.getString("Lokasi"), rs.getString("Kategori"), rs.getString("ISBN")});
                } while (rs.next());
                
            } else {
                System.out.println("Data tidak ada");
            }
            TablePerpus.setDefaultEditor(Object.class, null);
            TablePerpus.setModel(mTablePerpus);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void TablePerpusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePerpusMouseClicked
        // TODO add your handling code here:
        int baris = TablePerpus.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2){
            String Judul = TablePerpus.getValueAt(baris, 0).toString();
            txJudul.setText(Judul);
            String Tahun = TablePerpus.getValueAt(baris, 1).toString();
            txTahun.setText(Tahun);
            String Pengarang = TablePerpus.getValueAt(baris, 2).toString();
            txPengarang.setText(Pengarang);
            String Jenis = TablePerpus.getValueAt(baris, 3).toString();
            cbJenis.setSelectedItem(Jenis);
            String Lokasi = TablePerpus.getValueAt(baris, 4).toString();
            if(Lokasi.equalsIgnoreCase("Rak 1")) {
                rbRak1.setSelected(true);
            } else if(Lokasi.equalsIgnoreCase("Rak 2")) {
                rbRak2.setSelected(true);
            } else if(Lokasi.equalsIgnoreCase("Rak 3")) {
                rbRak3.setSelected(true);
            }
            String Kategori = TablePerpus.getValueAt(baris, 5).toString();
            if(Kategori.equalsIgnoreCase("Teknologi Bisnis Bahasa Sejarah")) {
                cbTeknologi.setSelected(true);
                cbBisnis.setSelected(true);
                cbBahasa.setSelected(true);
                cbSejarah.setSelected(true);
            }
            
            
            if(Kategori.equalsIgnoreCase("Teknologi Bisnis Bahasa ")) {
                cbTeknologi.setSelected(true);
                cbBisnis.setSelected(true);
                cbBahasa.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Teknologi Bisnis Sejarah")) {
                cbTeknologi.setSelected(true);
                cbBisnis.setSelected(true);
                cbSejarah.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Teknologi Bahasa Sejarah")) {
                cbTeknologi.setSelected(true);
                cbBahasa.setSelected(true);
                cbSejarah.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Bisnis Bahasa Sejarah")) {
                cbBisnis.setSelected(true);
                cbBahasa.setSelected(true);
                cbSejarah.setSelected(true);
            }
            
            // Teknologi Bisnis Bahasa Sejarah
            if(Kategori.equalsIgnoreCase("Teknologi Bisnis ")) {
                cbTeknologi.setSelected(true);
                cbBisnis.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Teknologi Bahasa ")) {
                cbTeknologi.setSelected(true);
                cbBahasa.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Teknologi Sejarah")) {
                cbTeknologi.setSelected(true);
                cbSejarah.setSelected(true);
            }
            
            if(Kategori.equalsIgnoreCase("Bisnis Bahasa ")) {
                cbBisnis.setSelected(true);
                cbBahasa.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Bisnis Sejarah")) {
                cbBisnis.setSelected(true);
                cbSejarah.setSelected(true);
            }
            
            if(Kategori.equalsIgnoreCase("Bahasa Sejarah")) {
                cbBahasa.setSelected(true);
                cbSejarah.setSelected(true);
            }
            
            
            if(Kategori.equalsIgnoreCase("Teknologi ")) {
                cbTeknologi.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Bisnis ")) {
                cbBisnis.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Bahasa ")) {
                cbBahasa.setSelected(true);
            }
            if(Kategori.equalsIgnoreCase("Sejarah")) {
                cbSejarah.setSelected(true);
            }

            String ISBN = TablePerpus.getValueAt(baris, 6).toString();
            txISBN.setText(ISBN);
        }
    }//GEN-LAST:event_TablePerpusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePerpus;
    private javax.swing.ButtonGroup bgRak;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbBahasa;
    private javax.swing.JCheckBox cbBisnis;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JCheckBox cbSejarah;
    private javax.swing.JCheckBox cbTeknologi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbRak1;
    private javax.swing.JRadioButton rbRak2;
    private javax.swing.JRadioButton rbRak3;
    private javax.swing.JTextField txISBN;
    private javax.swing.JTextField txJudul;
    private javax.swing.JTextField txPengarang;
    private javax.swing.JTextField txTahun;
    // End of variables declaration//GEN-END:variables
}
